import "./globals.css";
import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";

import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

const inter = Space_Grotesk({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "PAG Tech",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#fff]`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
